### ISSUE TITLE
Backspace button deletes characters on the right only

### ISSUE THREAD

**Issue by MarzukhAsjad** [Kernix13/WriterAssist#6]
Hi. I was tweaking with the live demo given on the README. I was unable to make letters be removed on the left by pressing the backspace button
![image](https://github.com/user-attachments/assets/279f948f-c3ca-4f29-843a-5a659a896b87)

I understand if it's a design principle, but would it be possible to add a configuration for it to be changed so that it can remove letters on the left as well if the user determines so? Thanks. If I have time, I will create a pull request as well.

**Comment by Kernix13** [comment]
That's the Delete key. I probably should have added a title of "Delete" for that key. That one only removes a character that is to the right of the cursor. The Backspace key removes characters to the left of the cursor - that key is to the left of the Delete key. I wanted to save space so I used icons for those keys as opposed to the words. 

The live version you are using is my original. If you are interested I updated that version to a TypeScript version and maybe some other features but I can't remember - it's been a while. That repo is [Typescript Virtual Keyboard](https://github.com/Kernix13/typescript-virtual-keyboard)

**Comment by MarzukhAsjad** [comment]
oh I see. My bad. the key on the left of that with the ← symbol is the backspace. Thanks a lot for pointing it out. I will check out the other one you linked as well. And cool job btw!

**Comment by Kernix13** [comment]
Thanks. I wasn't able to get the up and down arrows to work though. I also wasn't able to get Home and End to work for each line, only the beginning and end of the entire textarea

**Comment by MarzukhAsjad** [comment]
You could open another issue for the Home and End key feature. If I have some time, I will definitely take a look at it and make a pull request (if you are open to outside contributors)

**Comment by Kernix13** [comment]
I'm fine with contributors - I just created an issue for Home and End.
